defmodule NbJson.TypeScriptClient do
  @moduledoc """
  Generates dependency-free TypeScript fetch clients from `NbJson.Controller`
  contracts.

  `nb_ts` can include this client in a broader generated type bundle, but the
  generator lives here so `mix nb_json.gen.client` works in API-only projects
  without requiring a separate TypeScript package.
  """

  @doc """
  Generates TypeScript source for controller modules that use
  `NbJson.Controller`.
  """
  @spec to_typescript(module() | [module()], keyword()) :: binary()
  def to_typescript(modules, opts \\ [])

  def to_typescript(module, opts) when is_atom(module), do: to_typescript([module], opts)

  def to_typescript(modules, opts) when is_list(modules) do
    modules
    |> collect_endpoints()
    |> to_typescript_from_endpoints(opts)
  end

  @doc """
  Writes a generated TypeScript client file.
  """
  @spec write!(module() | [module()], Path.t(), keyword()) :: :ok
  def write!(modules, path, opts \\ []) do
    File.mkdir_p!(Path.dirname(path))
    File.write!(path, to_typescript(modules, opts))
  end

  @doc false
  @spec to_typescript_from_endpoints([{module(), map()}], keyword()) :: binary()
  def to_typescript_from_endpoints([], _opts), do: ""

  def to_typescript_from_endpoints(endpoints, opts) do
    [
      preamble(opts),
      serializer_imports(endpoints, opts),
      fallback_ref_aliases(endpoints, opts),
      json_api_types(endpoints),
      Enum.map_join(endpoints, "\n\n", &endpoint_types/1),
      Enum.map_join(endpoints, "\n\n", &endpoint_function/1)
    ]
    |> Enum.reject(&(&1 == ""))
    |> Enum.join("\n\n")
    |> Kernel.<>("\n")
  end

  defp collect_endpoints(modules) do
    modules
    |> Enum.flat_map(&module_endpoints/1)
    |> Enum.sort_by(fn {module, endpoint} -> {inspect(module), endpoint.name} end)
  end

  defp module_endpoints(module) do
    if Code.ensure_loaded?(module) and function_exported?(module, :__nb_json_endpoints__, 0) do
      module.__nb_json_endpoints__()
      |> Map.values()
      |> Enum.map(&{module, &1})
    else
      []
    end
  end

  defp preamble(opts) do
    title = Keyword.get(opts, :title, "nb_json API client")

    """
    /* #{title}
     * Generated by nb_json from controller contracts. Do not edit manually.
     */

    export type ApiError = {
      error: {
        code: string;
        message: string;
        status?: number;
        details?: unknown;
      };
    };

    export type ApiHeaders = Record<string, string>;

    export type ApiRequestOptions = {
      headers?: ApiHeaders;
      credentials?: "include" | "omit" | "same-origin";
      signal?: unknown;
      fetcher?: ApiFetcher;
    };

    export type ApiFetcher = (
      input: string,
      init: {
        method: string;
        headers?: ApiHeaders;
        body?: string;
        credentials?: "include" | "omit" | "same-origin";
        signal?: unknown;
      }
    ) => Promise<ApiFetchResponse>;

    export type ApiFetchResponse = {
      ok: boolean;
      status: number;
      statusText: string;
      json(): Promise<unknown>;
    };

    type QueryScalar = string | number | boolean | null | undefined;
    type QueryValue = QueryScalar | QueryValue[] | { [key: string]: QueryValue };

    declare const fetch: ApiFetcher;

    function buildPath(path: string, params?: object): string {
      return path
        .replace(/:([A-Za-z0-9_]+)/g, (_match, key) => encodePathParam(key, params))
        .replace(/\\{([^}]+)\\}/g, (_match, key) => encodePathParam(key, params));
    }

    function encodePathParam(key: string, params?: object): string {
      const source = params as Record<string, unknown> | undefined;
      const value = source?.[key];

      if (value === undefined || value === null) {
        throw new Error(`Missing path parameter: ${key}`);
      }

      return encodeURIComponent(String(value));
    }

    function appendQuery(path: string, params?: Record<string, QueryValue>): string {
      if (!params) return path;

      const query = new URLSearchParams();

      Object.entries(params).forEach(([key, value]) => {
        appendQueryValue(query, key, value);
      });

      const queryString = query.toString();
      return queryString ? `${path}${path.includes("?") ? "&" : "?"}${queryString}` : path;
    }

    function appendQueryValue(query: URLSearchParams, key: string, value: QueryValue): void {
      if (value === undefined || value === null) return;

      if (Array.isArray(value)) {
        value.forEach((item, index) => {
          const itemKey = isNestedQueryValue(item) ? `${key}[${index}]` : `${key}[]`;
          appendQueryValue(query, itemKey, item);
        });
        return;
      }

      if (typeof value === "object") {
        Object.entries(value).forEach(([childKey, childValue]) => {
          appendQueryValue(query, `${key}[${childKey}]`, childValue);
        });
        return;
      }

      query.append(key, String(value));
    }

    function isNestedQueryValue(value: QueryValue): value is QueryValue[] | { [key: string]: QueryValue } {
      return typeof value === "object" && value !== null;
    }

    function pickParams(params: object | undefined, keys: string[]): Record<string, unknown> {
      const source = params as Record<string, unknown> | undefined;
      const picked: Record<string, unknown> = {};

      keys.forEach((key) => {
        const value = source?.[key];
        if (value !== undefined) picked[key] = value;
      });

      return picked;
    }

    function hasKeys(value: Record<string, unknown>): boolean {
      return Object.keys(value).length > 0;
    }

    async function requestJson<T>(path: string, options: ApiRequestOptions & { method: string; body?: string } = { method: "GET" }): Promise<T> {
      const fetcher = options.fetcher ?? fetch;
      const { fetcher: _fetcher, ...requestOptions } = options;

      const response = await fetcher(path, {
        ...requestOptions,
        headers: {
          Accept: "application/json",
          ...requestOptions.headers,
        },
      });

      if (!response.ok) {
        throw await response.json().catch((): ApiError => ({
          error: {
            code: "request_failed",
            message: response.statusText,
            status: response.status,
          },
        }));
      }

      return response.json() as Promise<T>;
    }
    """
  end

  defp serializer_imports(endpoints, opts) do
    if Keyword.get(opts, :serializer_imports, true) do
      endpoints
      |> ref_modules()
      |> Enum.filter(&serializer_module?/1)
      |> Enum.map(fn module ->
        name = interface_name(module)
        filename = serializer_filename(module)
        ~s(import type { #{name} } from "./#{filename}";)
      end)
      |> Enum.sort()
      |> Enum.join("\n")
    else
      ""
    end
  end

  defp fallback_ref_aliases(endpoints, opts) do
    imported =
      if Keyword.get(opts, :serializer_imports, true) do
        endpoints
        |> ref_modules()
        |> Enum.filter(&serializer_module?/1)
        |> Enum.map(&interface_name/1)
        |> MapSet.new()
      else
        MapSet.new()
      end

    endpoints
    |> ref_modules()
    |> Enum.map(&interface_name/1)
    |> Enum.reject(&MapSet.member?(imported, &1))
    |> Enum.uniq()
    |> Enum.sort()
    |> Enum.map_join("\n", fn name -> "export type #{name} = Record<string, unknown>;" end)
  end

  defp json_api_types(endpoints) do
    if Enum.any?(endpoints, fn {_module, endpoint} -> json_api_endpoint?(endpoint) end) do
      """
      export type JsonApiResourceIdentifier = {
        type: string;
        id: string;
        meta?: Record<string, unknown>;
      };

      export type JsonApiRelationship<
        TData = JsonApiResourceIdentifier | JsonApiResourceIdentifier[] | null
      > = {
        data: TData;
        links?: Record<string, unknown>;
        meta?: Record<string, unknown>;
      };

      export type JsonApiResource<
        TAttributes = Record<string, unknown>,
        TRelationships = Record<string, JsonApiRelationship>
      > = {
        type: string;
        id?: string;
        attributes?: TAttributes;
        relationships?: TRelationships;
        links?: Record<string, unknown>;
        meta?: Record<string, unknown>;
      };
      """
    else
      ""
    end
  end

  defp ref_modules(endpoints) do
    endpoints
    |> Enum.flat_map(fn {_module, endpoint} ->
      endpoint.params ++ Enum.flat_map(endpoint.responses, &response_fields/1)
    end)
    |> Enum.flat_map(&refs_from_type(&1.type))
    |> Enum.uniq()
  end

  defp response_fields(%{kind: :success} = response), do: response.data ++ response.meta
  defp response_fields(_response), do: []

  defp json_api_endpoint?(endpoint) do
    Enum.any?(endpoint.responses, &match?(%{kind: :success, profile: :json_api}, &1))
  end

  defp endpoint_types({module, endpoint}) do
    prefix = type_prefix(module, endpoint)
    params_type = "#{prefix}Params"
    response_type = "#{prefix}Response"

    [
      params_interface(params_type, endpoint.params),
      response_interface(response_type, endpoint)
    ]
    |> Enum.reject(&(&1 == ""))
    |> Enum.join("\n\n")
  end

  defp params_interface(_name, []), do: ""

  defp params_interface(name, params) do
    """
    export interface #{name} {
    #{fields_to_typescript(params)}
    }
    """
  end

  defp response_interface(name, endpoint) do
    case Enum.find(endpoint.responses, &(&1.kind == :success)) do
      nil ->
        "export type #{name} = unknown;"

      %{profile: :json_api} = response ->
        json_api_response_interface(name, response)

      response ->
        meta =
          if response.meta == [] do
            ""
          else
            "\n  meta: {\n#{fields_to_typescript(response.meta, 4)}\n  };"
          end

        """
        export interface #{name} {
          data: {
        #{fields_to_typescript(response.data, 4)}
          };#{meta}
        }
        """
    end
  end

  defp json_api_response_interface(name, response) do
    data_field = List.first(response.data)

    meta =
      if response.meta == [] do
        ""
      else
        "\n  meta: {\n#{fields_to_typescript(response.meta, 4)}\n  };"
      end

    """
    export interface #{name} {
      data: #{json_api_data_typescript(data_field.type, response)};
      links?: Record<string, unknown>;
      included?: Array<JsonApiResource>;#{meta}
    }
    """
  end

  defp json_api_data_typescript({:list, inner}, response) do
    "Array<#{json_api_resource_typescript(inner, response)}>"
  end

  defp json_api_data_typescript(:list, response) do
    "Array<#{json_api_resource_typescript(:map, response)}>"
  end

  defp json_api_data_typescript(type, response), do: json_api_resource_typescript(type, response)

  defp json_api_resource_typescript(type, response) do
    attributes = json_api_attributes_typescript(type)

    case json_api_relationships_typescript(response) do
      "" -> "JsonApiResource<#{attributes}>"
      relationships -> "JsonApiResource<#{attributes}, #{relationships}>"
    end
  end

  defp json_api_attributes_typescript({:list, inner}), do: json_api_attributes_typescript(inner)
  defp json_api_attributes_typescript(:list), do: "Record<string, unknown>"
  defp json_api_attributes_typescript(type), do: type_to_typescript(type)

  defp json_api_relationships_typescript(response) do
    relationships =
      response
      |> Map.get(:json_api, [])
      |> Keyword.get(:relationships, [])

    cond do
      relationships in [nil, []] ->
        ""

      is_map(relationships) ->
        relationships |> Map.to_list() |> json_api_relationships_type_body()

      json_api_relationship_pairs?(relationships) ->
        json_api_relationships_type_body(relationships)

      true ->
        ""
    end
  end

  defp json_api_relationships_type_body(relationships) do
    fields =
      relationships
      |> Enum.map(fn {name, _config} -> "    #{property_name(name)}?: JsonApiRelationship;" end)
      |> Enum.join("\n")

    "{\n#{fields}\n  }"
  end

  defp json_api_relationship_pairs?(relationships) do
    Enum.all?(relationships, fn
      {name, _config} when is_atom(name) or is_binary(name) -> true
      _other -> false
    end)
  end

  defp endpoint_function({module, endpoint}) do
    prefix = type_prefix(module, endpoint)
    function_name = function_name(module, endpoint)
    params_type = "#{prefix}Params"
    response_type = "#{prefix}Response"
    method = String.upcase(endpoint.method)
    path = endpoint.path || "/#{endpoint.name}"
    params = endpoint.params
    query_keys = keys_for_location(params, :query)
    body_keys = keys_for_location(params, :body)
    needs_params? = params != []
    params_optional? = Enum.all?(params, &param_optional?/1)

    params_arg =
      cond do
        !needs_params? -> ""
        params_optional? -> "params: #{params_type} = {}, "
        true -> "params: #{params_type}, "
      end

    url_expr =
      case query_keys do
        [] ->
          ~s|buildPath("#{path}", #{if needs_params?, do: "params", else: "undefined"})|

        _ ->
          ~s|appendQuery(buildPath("#{path}", params), pickParams(params, #{inspect(query_keys)}) as Record<string, QueryValue>)|
      end

    body_setup =
      case body_keys do
        [] -> ""
        _ -> "  const body = pickParams(params, #{inspect(body_keys)});\n"
      end

    body_option =
      case body_keys do
        [] -> ""
        _ -> "\n    ...(hasKeys(body) ? { body: JSON.stringify(body) } : {}),"
      end

    content_type =
      case body_keys do
        [] -> ""
        _ -> "\n      \"Content-Type\": \"application/json\","
      end

    """
    export function #{function_name}(#{params_arg}options: ApiRequestOptions = {}): Promise<#{response_type}> {
    #{body_setup}  return requestJson<#{response_type}>(#{url_expr}, {
        ...options,
        method: "#{method}",#{body_option}
        headers: {#{content_type}
          ...options.headers,
        },
      });
    }
    """
  end

  defp keys_for_location(params, location) do
    params
    |> Enum.filter(&((&1.location || :query) == location))
    |> Enum.map(&Atom.to_string(&1.name))
  end

  defp fields_to_typescript(fields, indent \\ 2) do
    padding = String.duplicate(" ", indent)

    fields
    |> Enum.map(fn field ->
      optional = if param_optional?(field), do: "?", else: ""
      "#{padding}#{property_name(field.name)}#{optional}: #{type_to_typescript(field.type)};"
    end)
    |> Enum.join("\n")
  end

  defp type_to_typescript(:string), do: "string"
  defp type_to_typescript(:uuid), do: "string"
  defp type_to_typescript(:date), do: "string"
  defp type_to_typescript(:datetime), do: "string"
  defp type_to_typescript(:decimal), do: "string"
  defp type_to_typescript(:integer), do: "number"
  defp type_to_typescript(:float), do: "number"
  defp type_to_typescript(:number), do: "number"
  defp type_to_typescript(:boolean), do: "boolean"
  defp type_to_typescript(:map), do: "Record<string, unknown>"
  defp type_to_typescript(:list), do: "unknown[]"
  defp type_to_typescript(:any), do: "unknown"
  defp type_to_typescript({:ref, module}), do: interface_name(module)
  defp type_to_typescript({:list, inner}), do: "Array<#{type_to_typescript(inner)}>"

  defp type_to_typescript({:enum, values}),
    do: Enum.map_join(values, " | ", &literal_to_typescript/1)

  defp type_to_typescript({:literal, value}), do: literal_to_typescript(value)
  defp type_to_typescript({:nullable, inner}), do: "#{type_to_typescript(inner)} | null"
  defp type_to_typescript({:optional, inner}), do: type_to_typescript(inner)
  defp type_to_typescript({:union, types}), do: Enum.map_join(types, " | ", &type_to_typescript/1)
  defp type_to_typescript({:typescript_validated, ts_string}), do: ts_string
  defp type_to_typescript(type) when is_binary(type), do: type

  defp type_to_typescript({:shape, fields}) do
    inner =
      fields
      |> Enum.map(fn {name, type} ->
        optional = if optional_type?(type), do: "?", else: ""

        "  #{property_name(name)}#{optional}: #{type |> unwrap_optional() |> type_to_typescript()};"
      end)
      |> Enum.join("\n")

    "{\n#{inner}\n}"
  end

  defp type_to_typescript(_type), do: "unknown"

  defp refs_from_type({:ref, module}), do: [module]
  defp refs_from_type({:list, inner}), do: refs_from_type(inner)
  defp refs_from_type({:nullable, inner}), do: refs_from_type(inner)
  defp refs_from_type({:optional, inner}), do: refs_from_type(inner)
  defp refs_from_type({:union, types}), do: Enum.flat_map(types, &refs_from_type/1)

  defp refs_from_type({:shape, fields}),
    do: fields |> Keyword.values() |> Enum.flat_map(&refs_from_type/1)

  defp refs_from_type(_type), do: []

  defp param_optional?(%{optional: true}), do: true
  defp param_optional?(%{type: {:optional, _inner}}), do: true
  defp param_optional?(field), do: Map.has_key?(field, :default)

  defp optional_type?({:optional, _inner}), do: true
  defp optional_type?(_type), do: false

  defp unwrap_optional({:optional, inner}), do: inner
  defp unwrap_optional(type), do: type

  defp literal_to_typescript(value) when is_binary(value), do: inspect(value)
  defp literal_to_typescript(value) when is_atom(value), do: inspect(Atom.to_string(value))
  defp literal_to_typescript(value) when is_number(value), do: to_string(value)
  defp literal_to_typescript(true), do: "true"
  defp literal_to_typescript(false), do: "false"
  defp literal_to_typescript(nil), do: "null"
  defp literal_to_typescript(value), do: inspect(to_string(value))

  defp type_prefix(module, endpoint) do
    controller =
      module
      |> Module.split()
      |> List.last()
      |> String.replace_suffix("Controller", "")

    controller <> Macro.camelize(Atom.to_string(endpoint.name))
  end

  defp function_name(module, endpoint) do
    prefix = type_prefix(module, endpoint)
    <<first::binary-size(1), rest::binary>> = prefix
    String.downcase(first) <> rest
  end

  defp interface_name(module) do
    Code.ensure_loaded?(module)

    custom_name =
      if function_exported?(module, :__nb_serializer_typescript_name__, 0) do
        module.__nb_serializer_typescript_name__()
      end

    namespace =
      if function_exported?(module, :__nb_serializer_typescript_namespace__, 0) do
        module.__nb_serializer_typescript_namespace__()
      end

    cond do
      is_binary(custom_name) -> custom_name
      is_binary(namespace) -> namespace <> default_interface_name(module)
      true -> default_interface_name(module)
    end
  end

  defp default_interface_name(module) do
    module
    |> Module.split()
    |> List.last()
    |> String.replace_suffix("Serializer", "")
  end

  defp serializer_filename(module) do
    base = module |> Module.split() |> List.last()

    if function_exported?(module, :__nb_serializer_typescript_namespace__, 0) do
      case module.__nb_serializer_typescript_namespace__() do
        nil -> base
        namespace when is_binary(namespace) -> "#{namespace}#{base}"
      end
    else
      base
    end
  end

  defp serializer_module?(module) when is_atom(module) do
    Code.ensure_loaded?(module) and
      function_exported?(module, :__nb_serializer_type_metadata__, 0)
  end

  defp serializer_module?(_module), do: false

  defp property_name(atom) when is_atom(atom), do: atom |> Atom.to_string() |> property_name()

  defp property_name(value) when is_binary(value) do
    if Regex.match?(~r/^[A-Za-z_$][A-Za-z0-9_$]*$/, value) do
      value
    else
      inspect(value)
    end
  end
end
