defmodule NbJson.TypeScriptClientTest do
  use ExUnit.Case

  import ExUnit.CaptureIO

  defmodule UserSerializer do
    def __nb_serializer_type_metadata__ do
      %{
        fields: [
          %{name: :id, type: :uuid, opts: []},
          %{name: :name, type: :string, opts: []}
        ]
      }
    end
  end

  defmodule UsersController do
    use NbJson.Controller

    json_endpoint :health, method: :get, path: "/api/health" do
      response 200 do
        data(:ok, :boolean)
      end
    end

    json_endpoint :index, method: :get, path: "/api/users" do
      params do
        flop_params(pagination: :all)
      end

      response 200 do
        data(:users, list_of(ref(UserSerializer)))
        flop_meta()
      end
    end

    json_endpoint :show, method: :get, path: "/api/users/:id" do
      params do
        field(:id, :uuid, location: :path)
        field(:include, list_of(enum([:posts, :teams])), optional: true, location: :query)
      end

      response 200 do
        data(:user, ref(UserSerializer))
      end
    end

    json_endpoint :json_api_show, method: :get, path: "/api/json-api/users/:id" do
      params do
        field(:id, :uuid, location: :path)
      end

      response 200,
        profile: :json_api,
        type: "users",
        relationships: [team: [type: "teams"]] do
        data(:user, ref(UserSerializer))
      end
    end

    json_endpoint :create, method: :post, path: "/api/users" do
      params do
        field(:name, :string, location: :body)
        field(:active, :boolean, default: true, location: :body)

        field(:profile, shape(timezone: :string, locale: optional(:string)),
          optional: true,
          location: :body
        )
      end

      response 201 do
        data(:id, :uuid)
      end
    end

    json_endpoint :logout, method: :delete, path: "/api/session" do
      response 200 do
        data(:ok, :boolean)
      end
    end
  end

  test "generates request and response types plus fetch helpers" do
    ts = NbJson.TypeScriptClient.to_typescript(UsersController)

    assert ts =~ "Generated by nb_json from controller contracts"
    refute ts =~ "@tanstack/react-query"
    assert ts =~ "export type ApiAuthProvider"
    assert ts =~ "| ApiHeaders"
    assert ts =~ "auth?: ApiAuthProvider;"
    assert ts =~ "async function resolveAuthHeaders"
    assert ts =~ "return { Authorization: value.startsWith"
    assert ts =~ "...authHeaders"
    assert ts =~ ~s|import type { User } from "./UserSerializer";|
    assert ts =~ "export interface UsersIndexParams"
    assert ts =~ "page?: number;"
    assert ts =~ "filters?: Array<{"
    assert ts =~ "field: string;"
    assert ts =~ "value: unknown;"
    assert ts =~ "users: Array<User>;"
    assert ts =~ "pagination?: {"

    assert ts =~
             ~s|export function usersIndex(params: UsersIndexParams = {}, options: ApiRequestOptions = {}): Promise<UsersIndexResponse>|

    assert ts =~ ~s|appendQuery(buildPath("/api/users", params), pickParams(params, [|

    for key <- [
          "page",
          "page_size",
          "limit",
          "offset",
          "first",
          "last",
          "after",
          "before",
          "order_by",
          "order_directions",
          "filters"
        ] do
      assert ts =~ inspect(key)
    end

    assert ts =~ ~s|appendQueryValue(query, `${key}[${childKey}]`, childValue);|
    assert ts =~ ~s|const itemKey = isNestedQueryValue(item) ? `${key}[${index}]` : `${key}[]`;|
  end

  test "generates path params, query params, and JSON request bodies" do
    ts = NbJson.TypeScriptClient.to_typescript(UsersController)

    assert ts =~ "export interface UsersShowParams"
    assert ts =~ "id: string;"
    assert ts =~ ~s/include?: Array<"posts" | "teams">;/

    assert ts =~
             ~s|appendQuery(buildPath("/api/users/:id", params), pickParams(params, ["include"]) as Record<string, QueryValue>)|

    assert ts =~ "export interface UsersCreateParams"
    assert ts =~ "active?: boolean;"
    assert ts =~ "locale?: string;"
    assert ts =~ ~s|const body = pickParams(params, ["name", "active", "profile"]);|
    assert ts =~ ~s|method: "POST"|
    assert ts =~ ~s|"Content-Type": "application/json"|
  end

  test "generates JSON:API response types from response profiles" do
    ts = NbJson.TypeScriptClient.to_typescript(UsersController)

    assert ts =~ "export type JsonApiResourceIdentifier"
    assert ts =~ "export type JsonApiRelationship"
    assert ts =~ "export type JsonApiResource"
    assert ts =~ "export interface UsersJsonApiShowResponse"
    assert ts =~ "data: JsonApiResource<User, {"
    assert ts =~ "team?: JsonApiRelationship;"
    assert ts =~ "included?: Array<JsonApiResource>;"
  end

  test "can generate React Query hooks and option factories" do
    ts = NbJson.TypeScriptClient.to_typescript(UsersController, react_query: true)

    assert ts =~ ~s|from "@tanstack/react-query";|
    assert ts =~ "export type ApiQueryOptions"
    assert ts =~ "export type ApiMutationOptions"

    assert ts =~ ~s|export const usersIndexQueryRootKey = () => ["usersIndex"] as const;|
    assert ts =~ ~s|export const usersIndexQueryKey = (params: UsersIndexParams = {}) =>|
    assert ts =~ ~s|[...usersIndexQueryRootKey(), params] as const|
    assert ts =~ "export function usersIndexQueryOptions"

    assert ts =~
             "return tanstackQueryOptions<UsersIndexResponse, ApiError, UsersIndexResponse, ReturnType<typeof usersIndexQueryKey>>({"

    assert ts =~ "queryFn: () => usersIndex(params, request)"
    assert ts =~ "export function useUsersIndex("
    assert ts =~ "return useQuery({"

    assert ts =~ ~s|export const usersHealthQueryRootKey = () => ["usersHealth"] as const;|
    assert ts =~ "export const usersHealthQueryKey = () =>"
    assert ts =~ ~s|usersHealthQueryRootKey();|
    assert ts =~ "export function usersHealthQueryOptions(request: ApiRequestOptions = {})"
    assert ts =~ "queryFn: () => usersHealth(request)"

    assert ts =~ "export type UsersCreateVariables = UsersCreateParams;"
    assert ts =~ ~s|export const usersCreateMutationKey = () => ["usersCreate"] as const;|
    assert ts =~ "export function usersCreateMutationOptions"
    assert ts =~ "mutationFn: (params: UsersCreateVariables) => usersCreate(params, request)"
    assert ts =~ "export function useUsersCreate("
    assert ts =~ "return useMutation({"

    assert ts =~ "export type UsersLogoutVariables = void;"
    assert ts =~ "mutationFn: () => usersLogout(request)"
  end

  test "can generate standalone fallback aliases without serializer imports" do
    ts = NbJson.TypeScriptClient.to_typescript(UsersController, serializer_imports: false)

    refute ts =~ "import type"
    assert ts =~ "export type User = Record<string, unknown>;"
    assert ts =~ "users: Array<User>;"
  end

  test "writes generated clients to disk" do
    output_dir =
      Path.join(
        System.tmp_dir!(),
        "nb_json_type_script_client_#{System.unique_integer([:positive])}"
      )

    path = Path.join(output_dir, "api.ts")
    Process.put(:nb_json_type_script_client_output_dir, output_dir)

    assert :ok = NbJson.TypeScriptClient.write!(UsersController, path, serializer_imports: false)
    assert File.read!(path) =~ "export function usersIndex"
  after
    if output_dir = Process.get(:nb_json_type_script_client_output_dir) do
      File.rm_rf(output_dir)
    end
  end

  test "mix task writes generated clients" do
    output_dir =
      Path.join(
        System.tmp_dir!(),
        "nb_json_gen_client_task_#{System.unique_integer([:positive])}"
      )

    path = Path.join(output_dir, "api.ts")
    Process.put(:nb_json_gen_client_task_output_dir, output_dir)
    Mix.Task.reenable("nb_json.gen.client")

    output =
      capture_io(fn ->
        Mix.Tasks.NbJson.Gen.Client.run([
          inspect(UsersController),
          "--output",
          path,
          "--react-query",
          "--no-serializer-imports"
        ])
      end)

    assert output =~ "Generated #{path}"
    assert File.read!(path) =~ "export function usersIndex"
    assert File.read!(path) =~ "export function useUsersIndex"
  after
    if output_dir = Process.get(:nb_json_gen_client_task_output_dir) do
      File.rm_rf(output_dir)
    end
  end
end
